### ISSUE TITLE
Little Typo in Table Overview

### ISSUE THREAD

**Issue by cronventis** [angular/material2-docs-content#10]
Here is a little Typo:

https://github.com/angular/material2-docs-content/blob/6d256565645eace6b4ef805b35cdd9052c3eb488/docs-content/overviews/material/table.html#L310

It should be <code>&lt;tr mat-row&gt;</code> not <code>&lt;tr mat-row</code>&gt;

**Comment by Splaktar** [comment]
Fixed in https://github.com/angular/components/pull/18557.
