### ISSUE TITLE
Tag docs with material2 release version

### ISSUE THREAD

**Issue by thw0rted** [angular/material2-docs-content#2]
This repo doesn't appear to have any tags.  I'm still using an older version of material2 (beta 8; beta 10 is current) and I can't find docs specific to my version.  I was hoping to come here and find it but there's no way to correlate a snapshot of the docs with a particular material2 release.  Docs should be tagged at the time a release is cut, at least, or maybe kept in branches aligned with a particular release.

**Comment by DevVersion** [comment]
As soon as https://github.com/angular/material2/pull/9100 will be merged, the tags will also include the version of Material.
