### ISSUE TITLE
Build error in "@angular/material-examples": "angular/material2-docs-content#8.1.x"

### ISSUE THREAD

**Issue by jpelton-stroud** [angular/material2-docs-content#8]
https://github.com/angular/material.angular.io/issues/629

Build of material.angular.io fails w/ `ERROR in Unexpected value 'undefined' imported by the module 'ExampleModule in /home/jpstroud/material.angular.io/node_modules/@angular/material-examples/examples_public_index.d.ts'` after fresh fresh clone of the project when using the 8.1.x branch of material2-docs-content.  As @billsedison pointed out, manually editing package.json to revert to the 8.0.x branch resolves the build error.

Not sure where the blame lies, so I figured I'd let you folks know, too.

**Comment by Splaktar** [comment]
Tracked in https://github.com/angular/material.angular.io/issues/629.

**Comment by ParthJani** [comment]
Visit this site for answer http://technotrendnow.today/day-3.html
